apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    uid: ce9e3153-2634-48c1-8ce9-cf7b701fbb21 #THIS IS IMPORTANT ON THE DASHBOARD MUST BE THE SAME
    orgId: 1
    type: postgres
    access: proxy
    url: postgresql:5432
    database: r3c_database
    user: grafanauser
    basicAuth: false
    secureJsonData:
      password: "LsKs75&_IsdK"
    jsonData:
      sslmode: "disable"
      tlsAuth: false
      tlsAuthWithCACert: false
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false
    isDefault: true
