{
 "title": "R3C General",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "selected_site",
    "label": "Selectionnez le site",
    "query": "SELECT location_name FROM locations\nINNER JOIN device_info ON device_info.location_id = locations.location_id"
   },
   {
    "name": "selected_device_id",
    "label": "Select device",
    "query": "SELECT device_id FROM device_info\nWHERE device_info.device_name LIKE '$selected_device_name'"
   },
   {
    "name": "selected_device_name",
    "label": "Selectionnez le nom de l'appareil",
    "query": "SELECT device_name FROM device_info\nINNER JOIN locations ON locations.location_id = device_info.location_id\nWHERE locations.location_name LIKE '$selected_site'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center\">\n    <img src=\"/public/img/r3c/R3C_Logo_1.png\">\n</div>\n"
   }
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"temperature\")",
     "rawSql": "SELECT temperature, horodatage FROM data\nWHERE device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "ID de l'appareil : $selected_device_id",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 16, "y": 0 }
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "description": "Qualité de la connexion",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"battery\")",
     "rawSql": "SELECT rssi FROM data\nWHERE horodatage IN (SELECT MAX(horodatage) FROM data) AND device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Dernière mise à jour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(horodatage) FROM data\nWHERE device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"battery\")",
     "rawSql": "SELECT battery, horodatage FROM data \nWHERE device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"battery\")",
     "rawSql": "SELECT battery FROM data\nWHERE horodatage IN (SELECT MAX(horodatage) FROM data) AND device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"humidity\")",
     "rawSql": "SELECT humidity, horodatage FROM data\nWHERE device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Humidité",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"humidity\")",
     "rawSql": "SELECT humidity FROM data\nWHERE horodatage IN (SELECT MAX(horodatage) FROM data) AND device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "title": "Température",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"R3Cbucket\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"v3/sae4@ttn/devices/eui-a8610a34323d8811/up\")\n  |> filter(fn: (r) => r._field == \"temperature\")\n  |> last()",
     "rawSql": "SELECT temperature FROM data\nWHERE horodatage IN (SELECT MAX(horodatage) FROM data) AND device_id LIKE '$selected_device_id'"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"text-align: center;height: 20%\">\n    <h2><b>Développé par l'IUT BREST MORLAIX</b></h2>\n    <br>\n    <img src=\"/public/img/r3c/logo-iut.png\" style='height: 100%'>\n    <br>\n    <br>\n    <b>2024 LECERF AUGUSTIN, LE COSSEC ARNAUD, PRIGENT MORGAN</b>\n</div>"
   }
  }
 ]
}