{
 "title": "Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Appareils enregistrés",
   "type": "table",
   "gridPos": { "h": 17, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT data.device_id AS \"Device EUI\", device_info.device_name AS \"Device name\", locations.location_name AS \"Site\",  MAX(data.horodatage) AS \"Dernière mise à jour\", now()-MAX(data.horodatage) AS \"Temps depuis la dernière activité\"\nFROM data, device_info\nLEFT JOIN locations ON locations.location_id = device_info.location_id\nGROUP BY data.device_id, device_info.device_name, locations.location_name"
    }
   ]
  },
  {
   "title": "Ajouter/Modifier les informations d'un appareil",
   "type": "volkovlabs-form-panel",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT device_id FROM data "
    },
    { "rawSql": "SELECT * FROM locations " }
   ]
  },
  {
   "title": "Sites enregistrés",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT location_name FROM locations "
    }
   ]
  },
  { "title": "Ajout d'un site", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 } },
  { "title": "Alertes", "type": "alertlist", "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 } }
 ]
}